🏗️ Build spider: WAMPO – Transportation Policy Body
City-Bureau/city-scrapers-wichita pull request #15
Opened 2024-03-14 19:09 UTC by SimmonsRitchie

## What's this PR do?
Adds a spider to scrape meetings from the website of Wichita Area Metropolitan Planning Organization - Transportation Policy Body. The new spider is called `wicks_wampo_tpb`.

_[**Note:** Much like a separate PR, I accidentally merged this to main before review. Silly me 😒. Here's the original PR #13 and the revert #14 ]_

## Why are we doing this?
Requested by our site partners.

## Steps to manually test

1. Ensure the project is installed:
```
pipenv sync --dev
```
2. Activate the virtual env and enter the pipenv shell:
```
pipenv shell
```
3. Run the spider:
```
scrapy crawl wicks_wampo_tpb -O test_output.csv
```
4. Monitor the output and ensure no errors are raised.

5. Inspect `test_output.csv` to ensure the data looks valid. Target website is [here](https://www.wampo.org/transportation-policy-body).

## Are there any smells or added technical debt to note?
- Page is lacking some key details but has great links for attachments. Certain details are hardcoded.

2024-03-19 05:11 UTC, LienDang commented on tests/test_wicks_wampo_tpb.py
> +        {"href": "https://youtu.be/LsMI1EClvnI", "title": "cording"},
These 2 links should be unified into a single link: 
```json
{"href": "https://youtu.be/LsMI1EClvnI", "title": "Recording"}
```

2024-03-19 05:15 UTC, LienDang commented on tests/test_wicks_wampo_tpb.py
> +        {"href": "https://youtu.be/LsMI1EClvnI", "title": "cording"},
@SimmonsRitchie I noticed that the page renders complex html structure for a single link, eg. for [Agenda](https://www.wampo.org/_files/ugd/bbf89d_bc9c575ffcd9480ca7bd7b8c7611857b.pdf) link
<img width="1684" alt="WAMPO_Agenda_link" src="https://github.com/City-Bureau/city-scrapers-wichita/assets/1421838/09eea09a-b322-4ba5-be92-0208a769d831">
And for [Recording](https://youtu.be/LsMI1EClvnI) link, it breaks into 2 `<a>` elements. So I think you should rework on the `_parse_links` function.

2024-03-19 05:19 UTC, LienDang requested changes
Please fix these 2 functions:

```python
test_links()

_parse_links(item)
```

2024-03-19 16:43 UTC, SimmonsRitchie commented
> Please fix these 2 functions:
> 
> ```python
> test_links()
> 
> _parse_links(item)
> ```

Ah, my bad, @LienDang. That's sloppy work on my part. I'm experimenting with a new automation to build tests quickly and I'll admit I gave the links retrieved a pretty cursory look. I've now fixed the parsing to handle the messiness of this agency's HTML. I think it now works pretty well.

2024-03-20 01:52 UTC, LienDang approved these changes
LGTM

2024-03-20 15:07 UTC, merged